name: Ark
version: 0.0.1
api-version: 1.19
author: faiz
main: io.github.faiz.ark.Main
libraries:
  - io.github.monun:invfx-core:3.2.0
  - org.jetbrains.kotlin:kotlin-stdlib:1.5.21
  - org.jetbrains.kotlin:kotlin-reflect:1.5.21
  - org.jetbrains.kotlinx:kotlinx-coroutines-core:1.5.0
depend:
  - PlayerNPC